export const THEMES = {
  paper: {
    name:"Paper",bg:"#f5f0e8",fg:"#3a3a3a",muted:"#8a8070",accent:"#c0623a",
    ok:"#5a8a4a",gridBg:"#ebe6dc",gridBorder:"#d5cfc3",wallBg:"#8a8070",
    wall:"🧱",chip:"💎",exit:"🏁",player:"🧑",crawler:"🕷️",
    keyRed:"🔑",keyBlue:"🗝️",keyGreen:"🔑",keyYellow:"🗝️",
    doorRed:"🚪",doorBlue:"🚪",doorGreen:"🚪",doorYellow:"🚪",
    fire:"🔥",water:"💧",ice:"🧊",
    bootsFire:"🥾",bootsWater:"🥾",bootsIce:"🥾",
    inputBg:"#ebe6dc",headerBg:"#ebe6dc",editorBg:"#ede8df",
    font:"'Courier New', monospace",lineHi:"#d8d0c0",
    keyRedBg:"#ffdddd",keyBlueBg:"#ddddff",keyGreenBg:"#ddffdd",keyYellowBg:"#ffffdd",
    doorRedBg:"#cc6666",doorBlueBg:"#6666cc",doorGreenBg:"#66cc66",doorYellowBg:"#cccc66",
    fireBg:"#ffaa66",waterBg:"#66aaff",iceBg:"#aaeeff",
  },
  retro: {
    name:"Retro",bg:"#fef6e4",fg:"#172c66",muted:"#8e8d8a",accent:"#f582ae",
    ok:"#00b894",gridBg:"#fef6e4",gridBorder:"#e0d9cc",wallBg:"#172c66",
    wall:"🟦",chip:"⭐",exit:"🚪",player:"😎",crawler:"👾",
    keyRed:"🔴",keyBlue:"🔵",keyGreen:"🟢",keyYellow:"🟡",
    doorRed:"🟥",doorBlue:"🟦",doorGreen:"🟩",doorYellow:"🟨",
    fire:"🔥",water:"🌊",ice:"❄️",
    bootsFire:"👟",bootsWater:"👟",bootsIce:"👟",
    inputBg:"#f9f1e1",headerBg:"#f9f1e1",editorBg:"#fdf3dc",
    font:"'Trebuchet MS', sans-serif",lineHi:"#f0e8d0",
    keyRedBg:"#ffcccc",keyBlueBg:"#ccccff",keyGreenBg:"#ccffcc",keyYellowBg:"#ffffcc",
    doorRedBg:"#dd5555",doorBlueBg:"#5555dd",doorGreenBg:"#55dd55",doorYellowBg:"#dddd55",
    fireBg:"#ff8844",waterBg:"#4488ff",iceBg:"#88ddff",
  },
  candy: {
    name:"Candy",bg:"#fff0f5",fg:"#4a2040",muted:"#b08a9a",accent:"#ff6b9d",
    ok:"#51cf66",gridBg:"#fff5f9",gridBorder:"#f0d0e0",wallBg:"#e891b0",
    wall:"🍬",chip:"🍭",exit:"🌈",player:"🐱",crawler:"🐛",
    keyRed:"🍒",keyBlue:"🫐",keyGreen:"🍏",keyYellow:"🍋",
    doorRed:"🎀",doorBlue:"🎀",doorGreen:"🎀",doorYellow:"🎀",
    fire:"🌶️",water:"🧃",ice:"🍦",
    bootsFire:"👠",bootsWater:"👠",bootsIce:"👠",
    inputBg:"#fff5f9",headerBg:"#fff0f5",editorBg:"#fff5f9",
    font:"'Georgia', serif",lineHi:"#ffe0ec",
    keyRedBg:"#ffddee",keyBlueBg:"#ddeeff",keyGreenBg:"#ddffdd",keyYellowBg:"#ffffdd",
    doorRedBg:"#ff99aa",doorBlueBg:"#99aaff",doorGreenBg:"#99ff99",doorYellowBg:"#ffff99",
    fireBg:"#ffbb99",waterBg:"#99ddff",iceBg:"#ccffff",
  },
  forest: {
    name:"Forest",bg:"#f0f4e8",fg:"#2d3a1a",muted:"#7a8a60",accent:"#d4813a",
    ok:"#5a9a3a",gridBg:"#e8eede",gridBorder:"#c5d0a8",wallBg:"#6a7a50",
    wall:"🌲",chip:"🍄",exit:"🏕️",player:"🦊",crawler:"🐺",
    keyRed:"🍁",keyBlue:"💠",keyGreen:"🍀",keyYellow:"🌻",
    doorRed:"🪵",doorBlue:"🪵",doorGreen:"🪵",doorYellow:"🪵",
    fire:"🔥",water:"💦",ice:"🪨",
    bootsFire:"🥾",bootsWater:"🥾",bootsIce:"🥾",
    inputBg:"#e8eede",headerBg:"#e8eede",editorBg:"#e5ecda",
    font:"'Palatino', serif",lineHi:"#d5ddbb",
    keyRedBg:"#ffddcc",keyBlueBg:"#cceeff",keyGreenBg:"#ccffcc",keyYellowBg:"#ffffcc",
    doorRedBg:"#aa6644",doorBlueBg:"#4466aa",doorGreenBg:"#44aa44",doorYellowBg:"#aaaa44",
    fireBg:"#ff9955",waterBg:"#5599ff",iceBg:"#aaddee",
  },
  terminal: {
    name:"Terminal",bg:"#0d1117",fg:"#c9d1d9",muted:"#8b949e",accent:"#58a6ff",
    ok:"#39d353",gridBg:"#0d1117",gridBorder:"#21262d",wallBg:"#1a1a2e",
    wall:"🧱",chip:"💎",exit:"🏁",player:"🧑",crawler:"🕷️",
    keyRed:"🔴",keyBlue:"🔵",keyGreen:"🟢",keyYellow:"🟡",
    doorRed:"🚪",doorBlue:"🚪",doorGreen:"🚪",doorYellow:"🚪",
    fire:"🔥",water:"💧",ice:"🧊",
    bootsFire:"🥾",bootsWater:"🥾",bootsIce:"🥾",
    inputBg:"#161b22",headerBg:"#161b22",editorBg:"#161b22",
    font:"'IBM Plex Mono', monospace",lineHi:"#1c2333",
    keyRedBg:"#442222",keyBlueBg:"#222244",keyGreenBg:"#224422",keyYellowBg:"#444422",
    doorRedBg:"#882222",doorBlueBg:"#222288",doorGreenBg:"#228822",doorYellowBg:"#888822",
    fireBg:"#663311",waterBg:"#113366",iceBg:"#225566",
  },
};
